### ISSUE TITLE
Not working on GTX 1060 mobile pascal GPU

### ISSUE THREAD

**Issue by kikislater** [RunGp/Nvidiux#30]
Nvidiux is not working on Asus G502VM with gtx1060.
Stuck on line 882 with error : 
AttributeError: 'NvidiuxApp' object has no attribute 'driverVersion' 

Nvidia driver is 384.90 on Manjaro with kernel 4.12

**Comment by RunGp** [comment]
Hi
Problem solved
Gtx 1060now  work with 1.4.4 version

RunGp
